### ISSUE TITLE
Delete button on loadouts doesn’t work

### ISSUE THREAD

**Issue by inexorableAce** [DestinyItemManager/iOS#12]
Tapping the delete button in the  loadout sheet or page does nothing. My assumption is that this is due to the confirmation dialogue we pop up here.

**Comment by kyleshay** [comment]
Ah thanks! I patched this but an having a heck of a time with the review process. #3

I'll give it another try with them

**Comment by bhollis** [comment]
Duplicate of DestinyItemManager/iOS#3

**Comment by kyleshay** [comment]
FYI looks like apple finally pushed the update! Should be fixed now.
